# Generated by Django 3.2.18 on 2023-06-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_basket', '0001_initial'),
        ('app_merch', '0001_initial'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='app_merch.offer', verbose_name='предложение'),
        ),
        migrations.AddField(
            model_name='cart',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='app_users.buyer', verbose_name='покупатель'),
        ),
    ]
