# Generated by Django 3.2.18 on 2023-03-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_buyer_views'),
        ('app_merch', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellers',
            field=models.ManyToManyField(related_name='products', through='app_merch.Offer', to='app_users.Seller'),
        ),
    ]
