# Generated by Django 3.2.18 on 2023-06-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0001_initial'),
        ('app_merch', '0020_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='set_of_products',
        ),
        migrations.AlterField(
            model_name='cartdiscount',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='app_basket.cart', unique=True, verbose_name='корзина'),
        ),
    ]
