# Generated by Django 4.1.3 on 2023-03-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='buyer',
        ),
        migrations.AddField(
            model_name='buyer',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='app_users.profile', verbose_name='покупатель'),
        ),
    ]
